# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 352e5022052aa05ebb0b4c2621a87a45d11d81639ca97b5669f6e0c55f89bfcd15b4e6d6404d73c24ec9e7d461b7ebcf3c5a8a879cf01c7e50c5449edf51fc8c

test:
  secret_key_base: db4f9cbb73ce415e3641dbbe2500dae7946cc8f187371ad6adc8e4c6af7b4db68d0851b8cd783ddb714e8daa79964398eb99dccd9e3c590fe68dc4044d0bbd89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
